<a href="https://colab.research.google.com/github/VanThiKimKhanh1203/Hoc_tang_cuong_2024/blob/main/adidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# I. Giới thiệu về tập dữ liệu

**1. Nguồn gốc**


Tập dữ liệu "ADIDAS.xlsx" chứa thông tin về doanh số bán hàng của Adidas. Dữ liệu có thể được thu thập từ hệ thống bán hàng của Adidas hoặc từ báo cáo tổng hợp của các nhà bán lẻ.

**2. Ý nghĩa của tập dữ liệu**


Tập dữ liệu giúp phân tích doanh số của Adidas theo từng khu vực, nhà bán lẻ, loại sản phẩm, cũng như các chỉ số tài chính quan trọng như tổng doanh thu, lợi nhuận vận hành và tỷ suất lợi nhuận. Nó có thể được sử dụng để:

Đánh giá hiệu suất bán hàng theo khu vực, nhà bán lẻ hoặc loại sản phẩm.
Dự đoán xu hướng doanh số trong tương lai.
Xác định sản phẩm bán chạy và chiến lược kinh doanh tối ưu.


**3. Các trường dữ liệu**
* Retailer: Tên nhà bán lẻ.
* Retailer ID: Mã định danh của nhà bán lẻ.
* Invoice Date: Ngày xuất hóa đơn bán hàng.
* Region: Khu vực bán hàng (ví dụ: Northeast).
* State: Bang nơi diễn ra giao dịch.
* City: Thành phố nơi sản phẩm được bán.
* Product: Loại sản phẩm Adidas (ví dụ: Men's Street Footwear).
* Price per Unit: Giá bán mỗi đơn vị sản phẩm.
* Units Sold: Số lượng sản phẩm đã bán.
* Total Sales: Tổng doanh thu từ việc bán sản phẩm.
* Operating Profit: Lợi nhuận vận hành thu được từ sản phẩm.
* Operating Margin: Biên lợi nhuận vận hành.
* Sales Method: Hình thức bán hàng (ví dụ: In-store, Online).

# II. Xác định vấn đề cần rút ra từ tập dữ liệu.

**1. Phân tích doanh số và các yếu tố ảnh hưởng**


* Sản phẩm nào có doanh số cao nhất?
* Khu vực nào có tổng doanh số lớn nhất?
* Mối quan hệ giữa giá bán và số lượng sản phẩm bán ra như thế nào?
* Loại sản phẩm nào có tỷ suất lợi nhuận cao nhất?


**2. Phân tích hiệu suất bán hàng theo khu vực**
* Khu vực nào có lợi nhuận vận hành cao nhất?
* Có sự chênh lệch doanh số giữa các bang hay không?
* Phân tích tác động của phương thức bán hàng (Online vs. In-store) đến doanh số.


**3. Dự đoán và tối ưu hóa chiến lược bán hàng**
* Dự đoán xu hướng doanh số trong tương lai dựa trên dữ liệu lịch sử.
* Đánh giá hiệu quả của từng nhà bán lẻ trong việc phân phối sản phẩm Adidas.
* Đề xuất chiến lược giá dựa trên dữ liệu doanh số và lợi nhuận.

# III. Xử lí dữ liệu.

In [14]:
import pandas as pd

# Đọc file Excel
file_path = "/content/drive/MyDrive/Đồ án - Phân tích dữ liệu với Python/ADIDAS.xlsx"  # Đường dẫn đến file
xls = pd.ExcelFile(file_path)  # Mở file Excel

# Đọc sheet cụ thể
df = pd.read_excel(xls, sheet_name="Data Sales Adidas")

# tổng quan dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   datetime64[ns]
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   float64
 8   Units Sold        9648 non-null   int64
 9   Total Sales       9648 non-null   float64
 10  Operating Profit  9648 non-null   float64
 11  Operating Margin  9648 non-null   float64
 12  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 980.0+ KB

In [15]:
# thống kê dữ liệu
df.describe()

,Retailer ID,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin
count,9.648000e+03,9648,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000
mean,1.173850e+06,2021-05-10 15:20:44.776119296,45.216625,256.930037,93273.437500,34425.244761,0.422991
min,1.128299e+06,2020-01-01 00:00:00,7.000000,0.000000,0.000000,0.000000,0.100000
25%,1.185732e+06,2021-02-17 00:00:00,35.000000,106.000000,4254.500000,1921.752500,0.350000
50%,1.185732e+06,2021-06-04 00:00:00,45.000000,176.000000,9576.000000,4371.420000,0.410000
75%,1.185732e+06,2021-09-16 00:00:00,55.000000,350.000000,150000.000000,52062.500000,0.490000
max,1.197831e+06,2021-12-31 00:00:00,110.000000,1275.000000,825000.000000,390000.000000,0.800000
std,2.636038e+04,NaN,14.705397,214.252030,141916.016727,54193.113713,0.097197

In [16]:
# đọc 5 hàng đầu
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store

In [17]:
# đọc 5 hàng cuối
df.tail()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
9643,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [19]:
# đọc 5 hàng bất kỳ
df.iloc[200:205]

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
200,West Gear,1128299,2021-02-05,West,California,San Francisco,Men's Street Footwear,55.0,875,481250.0,144375.0,0.30,Outlet
201,West Gear,1128299,2021-02-06,West,California,San Francisco,Men's Athletic Footwear,60.0,875,525000.0,78750.0,0.15,Outlet
202,West Gear,1128299,2021-02-07,West,California,San Francisco,Women's Street Footwear,55.0,725,398750.0,119625.0,0.30,Outlet
203,West Gear,1128299,2021-02-08,West,California,San Francisco,Women's Athletic Footwear,55.0,700,385000.0,96250.0,0.25,Outlet
204,West Gear,1128299,2021-02-09,West,California,San Francisco,Men's Apparel,65.0,650,422500.0,190125.0,0.45,Outlet

In [20]:
# lấy 5 hàng ngẫu nhiên
df.sample(5)

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
470,Foot Locker,1185732,2021-12-03,Northeast,Pennsylvania,Philadelphia,Men's Street Footwear,65.0,525,341250.0,187687.50,0.55,Outlet
5461,Foot Locker,1185732,2021-12-10,West,Wyoming,Cheyenne,Men's Apparel,54.0,145,7830.0,3523.50,0.45,Online
7280,Foot Locker,1185732,2021-03-13,Northeast,Delaware,Wilmington,Women's Apparel,39.0,72,2808.0,1404.00,0.50,Online
4091,West Gear,1128299,2021-02-08,West,California,San Francisco,Women's Athletic Footwear,53.0,210,11130.0,4452.00,0.40,Online
8368,Sports Direct,1197831,2021-08-21,South,Alabama,Birmingham,Women's Street Footwear,11.0,152,1672.0,785.84,0.47,Outlet

In [22]:
# lấy 5 hàng đầu tiên của cột Price per Unit
df["Price per Unit"].head()

0    50.0
1    50.0
2    40.0
3    45.0
4    60.0
Name: Price per Unit, dtype: float64

In [23]:
# lấy 5 hàng bất kỳ của 2 cột Units Sold và Total Sales
df[["Units Sold", "Total Sales"]].iloc[15:20]

    Units Sold  Total Sales
15         800     360000.0
16         850     510000.0
17         950     475000.0
18        1200     600000.0
19         900     450000.0

# Một số cách xử lý giá trị thiếu trong tập dữ liệu Adidas
**1. Loại bỏ hàng hoặc cột thiếu dữ liệu**
* Áp dụng khi số lượng giá trị thiếu ít, không ảnh hưởng lớn đến dữ liệu.
* Ví dụ: Xóa dòng nếu "Price per Unit" hoặc "Units Sold" bị thiếu quá ít, hoặc xóa cột nếu quá nhiều giá trị trống.

**2. Điền giá trị trung bình, trung vị hoặc mode**

* Trung bình: Dùng cho dữ liệu số như "Price per Unit" nếu có phân phối chuẩn.
* Trung vị: Dùng khi có ngoại lệ, ví dụ "Total Sales".
* Mode: Dùng cho dữ liệu phân loại, như "Region".

**3. Sử dụng giá trị trước hoặc sau**

* Phù hợp với dữ liệu theo thời gian.
* Ví dụ: Điền "Invoice Date" bị thiếu bằng ngày trước đó hoặc sau đó.

**4. Dự đoán giá trị thiếu bằng thuật toán**

* Áp dụng khi có đủ dữ liệu và cần dự đoán chính xác.
* Ví dụ: Dự đoán "Total Sales" dựa trên "Price per Unit" và "Units Sold" bằng hồi quy tuyến tính.

In [24]:
# Kiểm tra số lượng giá trị null của tất cả các trường
print(df.isnull().sum())

Retailer            0
Retailer ID         0
Invoice Date        0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Operating Margin    0
Sales Method        0
dtype: int64

In [28]:
# Điền giá trị NULL bằng trung vị của Price per Unit
df['Price per Unit'].fillna(df['Price per Unit'].median(), inplace=True)

<ipython-input-28-5a88346b9fda>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price per Unit'].fillna(df['Price per Unit'].median(), inplace=True)

In [29]:
# Kiểm tra lại
print(df.isnull().sum())  # Xác nhận không còn giá trị NULL

Retailer            0
Retailer ID         0
Invoice Date        0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Operating Margin    0
Sales Method        0
dtype: int64

# Một số phương pháp phát hiện giá trị ngoại lai trong tập dữ liệu Adidas
**1. Phương pháp IQR (Interquartile Range)**

* Xác định ngoại lai dựa trên khoảng tứ phân vị: Giá trị nằm ngoài khoảng (Q1 - 1.5IQR, Q3 + 1.5IQR) được coi là ngoại lai.
* Ứng dụng: Phát hiện giá trị bất thường trong "Price per Unit" hoặc "Total Sales".
* Ưu điểm: Dễ thực hiện, phù hợp với dữ liệu có phân phối chuẩn.

**2. Phương pháp Percentile Capping**

* Cắt bỏ các giá trị nằm ngoài phạm vi 1% - 99% để hạn chế ảnh hưởng của ngoại lai.
* Ứng dụng: Điều chỉnh giá trị bất thường trong "Units Sold" hoặc "Operating Profit".
* Ưu điểm: Giữ lại nhiều dữ liệu hơn so với IQR, tránh loại bỏ quá nhiều điểm dữ liệu quan trọng.

In [31]:
# Kiểm tra các chỉ số của cột Units Sold
print(df['Units Sold'].describe())

count    9648.000000
mean      256.930037
std       214.252030
min         0.000000
25%       106.000000
50%       176.000000
75%       350.000000
max      1275.000000
Name: Units Sold, dtype: float64

In [32]:
# xác định giá trị ngoại lai

# Tính các giá trị Q1, Q3 và IQR cho "Units Sold"
Q1 = df['Units Sold'].quantile(0.25)  # Phân vị thứ 25%
Q3 = df['Units Sold'].quantile(0.75)  # Phân vị thứ 75%
IQR = Q3 - Q1  # Khoảng tứ phân vị

# Xác định ngưỡng dưới và ngưỡng trên
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [33]:
# Lọc dữ liệu, chỉ giữ các giá trị hợp lệ
df_cleaned = df[(df['Units Sold'] >= lower_bound) & (df['Units Sold'] <= upper_bound)]

# Kiểm tra số dòng sau khi xử lý
print(f"Số dòng trước khi xử lý: {len(df)}")
print(f"Số dòng sau khi loại bỏ ngoại lai cột 'Units Sold': {len(df_cleaned)}")

Số dòng trước khi xử lý: 9648
Số dòng sau khi loại bỏ ngoại lai cột 'Units Sold': 9140

# Lọc dữ liệu theo điều kiện.

In [34]:
#Lấy các giá trị duy nhất trong cột "Region"
unique_values = df["Region"].unique()
print(unique_values)

['Northeast' 'South' 'West' 'Midwest' 'Southeast']

In [35]:
#Lọc các giao dịch có tổng doanh thu ("Total Sales") trên 50.000 USD
df_filtered = df[df["Total Sales"] > 50000]
print(df_filtered.head())

      Retailer  Retailer ID Invoice Date     Region     State      City  \
0  Foot Locker      1185732   2020-01-01  Northeast  New York  New York
1  Foot Locker      1185732   2020-01-02  Northeast  New York  New York
2  Foot Locker      1185732   2020-01-03  Northeast  New York  New York
3  Foot Locker      1185732   2020-01-04  Northeast  New York  New York
4  Foot Locker      1185732   2020-01-05  Northeast  New York  New York

                     Product  Price per Unit  Units Sold  Total Sales  \
0      Men's Street Footwear            50.0        1200     600000.0
1    Men's Athletic Footwear            50.0        1000     500000.0
2    Women's Street Footwear            40.0        1000     400000.0
3  Women's Athletic Footwear            45.0         850     382500.0
4              Men's Apparel            60.0         900     540000.0

   Operating Profit  Operating Margin Sales Method
0          300000.0              0.50     In-store
1          150000.0              0.30     In-store
2          140000.0              0.35     In-store
3          133875.0              0.35     In-store
4          162000.0              0.30     In-store

In [36]:
#Lọc các giao dịch tại khu vực "Northeast" có số lượng bán ("Units Sold") trên 1.000
df_filtered = df[(df["Region"] == "Northeast") & (df["Units Sold"] > 1000)]
print(df_filtered.head())

       Retailer  Retailer ID Invoice Date     Region     State      City  \
0   Foot Locker      1185732   2020-01-01  Northeast  New York  New York
6   Foot Locker      1185732   2020-01-07  Northeast  New York  New York
12  Foot Locker      1185732   2020-01-25  Northeast  New York  New York
18  Foot Locker      1185732   2020-01-31  Northeast  New York  New York
24  Foot Locker      1185732   2020-02-06  Northeast  New York  New York

                  Product  Price per Unit  Units Sold  Total Sales  \
0   Men's Street Footwear            50.0        1200     600000.0
6   Men's Street Footwear            50.0        1250     625000.0
12  Men's Street Footwear            50.0        1220     610000.0
18  Men's Street Footwear            50.0        1200     600000.0
24  Men's Street Footwear            60.0        1220     732000.0

    Operating Profit  Operating Margin Sales Method
0           300000.0               0.5     In-store
6           312500.0               0.5     In-store
12          305000.0               0.5       Outlet
18          300000.0               0.5       Outlet
24          366000.0               0.5       Outlet

# Sắp xếp dữ liệu

In [37]:
#Sắp xếp theo "Total Sales" giảm dần
df_sorted = df.sort_values(by="Total Sales", ascending=False)
print(df_sorted.head())

       Retailer  Retailer ID Invoice Date     Region      State         City  \
1970  West Gear      1128299   2021-06-17      South  Louisiana  New Orleans
1394    Walmart      1128299   2021-06-17  Southeast    Florida      Orlando
1395    Walmart      1128299   2021-07-16  Southeast    Florida      Orlando
1971  West Gear      1128299   2021-07-16      South  Louisiana  New Orleans
1977  West Gear      1128299   2021-08-17      South  Louisiana  New Orleans

                    Product  Price per Unit  Units Sold  Total Sales  \
1970        Women's Apparel           110.0         750     825000.0
1394        Women's Apparel           110.0         750     825000.0
1395  Men's Street Footwear            90.0         900     810000.0
1971  Men's Street Footwear            90.0         900     810000.0
1977  Men's Street Footwear            95.0         850     807500.0

      Operating Profit  Operating Margin Sales Method
1970          288750.0              0.35       Online
1394          371250.0              0.45     In-store
1395          243000.0              0.30     In-store
1971          324000.0              0.40       Online
1977          323000.0              0.40       Online

In [38]:
#Sắp xếp theo "Units Sold" tăng dần, nếu bằng nhau thì theo "Operating Profit" giảm dần
df_sorted = df.sort_values(by=["Units Sold", "Operating Profit"], ascending=[True, False])
print(df_sorted.head())

         Retailer  Retailer ID Invoice Date   Region     State   City  \
1019  Foot Locker      1185732   2021-06-05  Midwest  Nebraska  Omaha
1025  Foot Locker      1185732   2021-06-11  Midwest  Nebraska  Omaha
4907  Foot Locker      1185732   2021-06-05  Midwest  Nebraska  Omaha
4913  Foot Locker      1185732   2021-06-11  Midwest  Nebraska  Omaha
4914  Foot Locker      1185732   2021-06-12  Midwest  Nebraska  Omaha

                        Product  Price per Unit  Units Sold  Total Sales  \
1019  Women's Athletic Footwear            35.0           0          0.0
1025  Women's Athletic Footwear            30.0           0          0.0
4907  Women's Athletic Footwear            33.0           0          0.0
4913  Women's Athletic Footwear            27.0           0          0.0
4914              Men's Apparel            42.0           6        252.0

      Operating Profit  Operating Margin Sales Method
1019              0.00              0.40       Outlet
1025              0.00              0.40       Outlet
4907              0.00              0.55       Online
4913              0.00              0.53       Online
4914            120.96              0.48       Online

# Thêm hàng/cột

In [39]:
#Thêm một giao dịch mới vào cuối DataFrame
new_row = {
    "Retailer": "New Store",
    "Retailer ID": 9999,
    "Invoice Date": "2025-01-01",
    "Region": "Northeast",
    "State": "New York",
    "City": "NYC",
    "Product": "Men's Running Shoes",
    "Price per Unit": 120,
    "Units Sold": 500,
    "Total Sales": 60000,
    "Operating Profit": 15000,
    "Operating Margin": 0.25,
    "Sales Method": "Online"
}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
print(df.tail())  # Kiểm tra hàng mới thêm

         Retailer  Retailer ID         Invoice Date     Region          State  \
9644  Foot Locker      1185732  2021-01-24 00:00:00  Northeast  New Hampshire
9645  Foot Locker      1185732  2021-02-22 00:00:00  Northeast  New Hampshire
9646  Foot Locker      1185732  2021-02-22 00:00:00  Northeast  New Hampshire
9647  Foot Locker      1185732  2021-02-22 00:00:00  Northeast  New Hampshire
9648    New Store         9999           2025-01-01  Northeast       New York

            City                  Product  Price per Unit  Units Sold  \
9644  Manchester          Women's Apparel            41.0         105
9645  Manchester    Men's Street Footwear            41.0         184
9646  Manchester  Men's Athletic Footwear            42.0          70
9647  Manchester  Women's Street Footwear            29.0          83
9648         NYC      Men's Running Shoes           120.0         500

      Total Sales  Operating Profit  Operating Margin Sales Method
9644       4305.0           1377.60              0.32       Outlet
9645       7544.0           2791.28              0.37       Outlet
9646       2940.0           1234.80              0.42       Outlet
9647       2407.0            649.89              0.27       Outlet
9648      60000.0          15000.00              0.25       Online

In [40]:
#Thêm cột "profit_per_unit" (Lợi nhuận trên mỗi sản phẩm)
df["profit_per_unit"] = df["Operating Profit"] / df["Units Sold"]
print(df.head())

      Retailer  Retailer ID         Invoice Date     Region     State  \
0  Foot Locker      1185732  2020-01-01 00:00:00  Northeast  New York
1  Foot Locker      1185732  2020-01-02 00:00:00  Northeast  New York
2  Foot Locker      1185732  2020-01-03 00:00:00  Northeast  New York
3  Foot Locker      1185732  2020-01-04 00:00:00  Northeast  New York
4  Foot Locker      1185732  2020-01-05 00:00:00  Northeast  New York

       City                    Product  Price per Unit  Units Sold  \
0  New York      Men's Street Footwear            50.0        1200
1  New York    Men's Athletic Footwear            50.0        1000
2  New York    Women's Street Footwear            40.0        1000
3  New York  Women's Athletic Footwear            45.0         850
4  New York              Men's Apparel            60.0         900

   Total Sales  Operating Profit  Operating Margin Sales Method  \
0     600000.0          300000.0              0.50     In-store
1     500000.0          150000.0              0.30     In-store
2     400000.0          140000.0              0.35     In-store
3     382500.0          133875.0              0.35     In-store
4     540000.0          162000.0              0.30     In-store

   profit_per_unit
0            250.0
1            150.0
2            140.0
3            157.5
4            180.0

# Xóa một vài hàng dữ liệu với một số điều kiện

In [41]:
#Xóa các giao dịch có "Region" là "South"
df = df[df["Region"] != "South"]

In [42]:
#Xóa các hàng có "Price per Unit" < 50 và "Units Sold" > 1000
df = df[~((df["Price per Unit"] < 50) & (df["Units Sold"] > 1000))]

# Tìm kiếm giá trị theo điều kiện

In [43]:
#Tìm sản phẩm có "Total Sales" cao nhất
max_sales_row = df[df["Total Sales"] == df["Total Sales"].max()]
print(max_sales_row.head())

     Retailer  Retailer ID         Invoice Date     Region    State     City  \
1394  Walmart      1128299  2021-06-17 00:00:00  Southeast  Florida  Orlando

              Product  Price per Unit  Units Sold  Total Sales  \
1394  Women's Apparel           110.0         750     825000.0

      Operating Profit  Operating Margin Sales Method  profit_per_unit
1394          371250.0              0.45     In-store            495.0

In [44]:
#Tìm tất cả giao dịch có "City" là "Los Angeles"
df_LA = df[df["City"] == "Los Angeles"]
print(df_LA.head())

    Retailer  Retailer ID         Invoice Date Region       State  \
216   Kohl's      1189833  2021-03-11 00:00:00   West  California
217   Kohl's      1189833  2021-03-12 00:00:00   West  California
218   Kohl's      1189833  2021-03-13 00:00:00   West  California
219   Kohl's      1189833  2021-03-14 00:00:00   West  California
220   Kohl's      1189833  2021-03-15 00:00:00   West  California

            City                  Product  Price per Unit  Units Sold  \
216  Los Angeles            Men's Apparel            50.0         500
217  Los Angeles          Women's Apparel            45.0         700
218  Los Angeles    Men's Street Footwear            35.0         750
219  Los Angeles  Men's Athletic Footwear            45.0         650
220  Los Angeles  Women's Street Footwear            45.0         675

     Total Sales  Operating Profit  Operating Margin Sales Method  \
216     250000.0          137500.0              0.55       Outlet
217     315000.0           63000.0              0.20       Outlet
218     262500.0          105000.0              0.40       Outlet
219     292500.0           73125.0              0.25       Outlet
220     303750.0          121500.0              0.40       Outlet

     profit_per_unit
216            275.0
217             90.0
218            140.0
219            112.5
220            180.0